# -*- coding: utf-8 -*-
"""
Seed content for Koine.

Each deck is a dict:
    {
      "group":   menu section it appears under,
      "slug":    stable id used in URLs / imports,
      "name":    display name,
      "subtitle": short line under the name (optional),
      "cards":   list of (front, back, hint, extra) tuples.
                 front = the prompt (Greek, usually);
                 back  = the answer (gloss / definition);
                 hint  = transliteration or a nudge (optional);
                 extra = part of speech / grammatical note (optional).
    }

NOTE ON THE VOCABULARY: glosses are deliberately short study glosses, not full
lexicon entries. Frequency ranks are approximate and edition-dependent — treat
the banks as tiers, not exact rankings. Verify accents/breathings and nuance
against a real lexicon (BDAG, Mounce, or the free STEP Bible tagged text)
before relying on any single form. See the README for how to extend to 500.
"""

# --------------------------------------------------------------------------- #
# 1. ALPHABET
# --------------------------------------------------------------------------- #

_MINUSCULE = [
    ("α", "alpha — 'a' as in father", "a", "vowel"),
    ("β", "beta — 'b'", "b", "consonant"),
    ("γ", "gamma — hard 'g'; 'ng' before γ κ ξ χ", "g", "consonant"),
    ("δ", "delta — 'd'", "d", "consonant"),
    ("ε", "epsilon — short 'e' as in met", "e", "vowel"),
    ("ζ", "zeta — 'z' / 'dz'", "z", "consonant"),
    ("η", "eta — long 'e' as in obey", "ē", "vowel"),
    ("θ", "theta — 'th' as in thin", "th", "consonant"),
    ("ι", "iota — 'i' as in machine or bit", "i", "vowel"),
    ("κ", "kappa — 'k'", "k", "consonant"),
    ("λ", "lambda — 'l'", "l", "consonant"),
    ("μ", "mu — 'm'", "m", "consonant"),
    ("ν", "nu — 'n'", "n", "consonant"),
    ("ξ", "xi — 'x' (ks)", "x", "consonant"),
    ("ο", "omicron — short 'o' as in not", "o", "vowel"),
    ("π", "pi — 'p'", "p", "consonant"),
    ("ρ", "rho — 'r' (rolled)", "r", "consonant"),
    ("σ / ς", "sigma — 's'  (ς used at word end)", "s", "consonant"),
    ("τ", "tau — 't'", "t", "consonant"),
    ("υ", "upsilon — 'u' (French u / German ü)", "u / y", "vowel"),
    ("φ", "phi — 'ph' as in phone", "ph", "consonant"),
    ("χ", "chi — 'ch' as in Scottish loch", "ch", "consonant"),
    ("ψ", "psi — 'ps' as in lips", "ps", "consonant"),
    ("ω", "omega — long 'o' as in tone", "ō", "vowel"),
]

_UNCIAL = [
    ("Α", "alpha", "a", "vowel"),
    ("Β", "beta", "b", "consonant"),
    ("Γ", "gamma", "g", "consonant"),
    ("Δ", "delta", "d", "consonant"),
    ("Ε", "epsilon", "e", "vowel"),
    ("Ζ", "zeta", "z", "consonant"),
    ("Η", "eta", "ē", "vowel"),
    ("Θ", "theta", "th", "consonant"),
    ("Ι", "iota", "i", "vowel"),
    ("Κ", "kappa", "k", "consonant"),
    ("Λ", "lambda", "l", "consonant"),
    ("Μ", "mu", "m", "consonant"),
    ("Ν", "nu", "n", "consonant"),
    ("Ξ", "xi", "x", "consonant"),
    ("Ο", "omicron", "o", "vowel"),
    ("Π", "pi", "p", "consonant"),
    ("Ρ", "rho", "r", "consonant"),
    ("Σ", "sigma", "s", "consonant"),
    ("Τ", "tau", "t", "consonant"),
    ("Υ", "upsilon", "u / y", "vowel"),
    ("Φ", "phi", "ph", "consonant"),
    ("Χ", "chi", "ch", "consonant"),
    ("Ψ", "psi", "ps", "consonant"),
    ("Ω", "omega", "ō", "vowel"),
]

# --------------------------------------------------------------------------- #
# 2. GRAMMAR TERMS
# --------------------------------------------------------------------------- #

_PARTS_OF_SPEECH = [
    ("Noun (ὄνομα)", "Names a person, place, thing, or idea. Inflects for case, number, gender.", None, None),
    ("Verb (ῥῆμα)", "Expresses an action or state of being. Inflects for tense, voice, mood, person, number.", None, None),
    ("Adjective", "Describes or modifies a noun; agrees with it in case, number, and gender.", None, None),
    ("Adverb", "Modifies a verb, adjective, or another adverb. Usually uninflected.", None, None),
    ("Article", "ὁ, ἡ, τό — the definite article. Greek has no indefinite article ('a/an').", None, None),
    ("Pronoun", "Stands in place of a noun (e.g. αὐτός, οὗτος, ὅς).", None, None),
    ("Preposition", "Relates a noun/pronoun to another word and governs a particular case (e.g. ἐν + dative).", None, None),
    ("Conjunction", "Joins words, phrases, or clauses (e.g. καί, δέ, ἀλλά, ὅτι, ἵνα).", None, None),
    ("Particle", "A small, usually uninflected word adding nuance (e.g. ἄν, μέν, γε, δή).", None, None),
    ("Interjection", "An exclamation standing outside the grammar of the sentence (e.g. ἰδού, οὐαί).", None, None),
]

_CASES = [
    ("Nominative", "Case of the subject; also the predicate nominative.", None, "5 cases"),
    ("Genitive", "Possession, source, or separation — often 'of' or 'from'.", None, "5 cases"),
    ("Dative", "Indirect object; also means, location, and reference — 'to/for/with/in/by'.", None, "5 cases"),
    ("Accusative", "Case of the direct object; also extent of space or time.", None, "5 cases"),
    ("Vocative", "Case of direct address (calling someone).", None, "5 cases"),
]

_TENSES = [
    ("Present", "Ongoing / continuous action in present time (imperfective aspect).", None, "tense"),
    ("Imperfect", "Ongoing or repeated action in past time.", None, "tense"),
    ("Future", "Action expected in future time.", None, "tense"),
    ("Aorist", "Simple / undefined action, usually past (perfective aspect).", None, "tense"),
    ("Perfect", "Completed action with a continuing result or state.", None, "tense"),
    ("Pluperfect", "Completed past action whose result also lay in the past.", None, "tense"),
]

_VOICES = [
    ("Active", "The subject performs the action.", None, "voice"),
    ("Middle", "The subject acts on or for itself, or is closely involved in the action.", None, "voice"),
    ("Passive", "The subject receives the action.", None, "voice"),
]

_MOODS = [
    ("Indicative", "States a fact or asks a question — presents the action as real.", None, "mood"),
    ("Subjunctive", "Presents the action as probable or contingent (often with ἵνα, ἐάν).", None, "mood"),
    ("Optative", "Expresses a wish or remote possibility. Rare in the NT (e.g. μὴ γένοιτο).", None, "mood"),
    ("Imperative", "Gives a command, request, or prohibition.", None, "mood"),
]

_VERBALS = [
    ("Infinitive", "A verbal noun — 'to loose', 'to be'. Not limited by person/number.", None, "verbal"),
    ("Participle", "A verbal adjective — 'loosing', 'having been loosed'. Agrees like an adjective.", None, "verbal"),
]

_NUMBER_GENDER = [
    ("Singular", "One of something.", None, "number"),
    ("Plural", "More than one.", None, "number"),
    ("Masculine", "Grammatical gender — not always tied to natural gender.", None, "gender"),
    ("Feminine", "Grammatical gender.", None, "gender"),
    ("Neuter", "Grammatical gender ('neither'). Neuter plural subjects often take a singular verb.", None, "gender"),
    ("1st person", "The speaker(s): 'I / we'.", None, "person"),
    ("2nd person", "The one(s) addressed: 'you'.", None, "person"),
    ("3rd person", "The one(s) spoken about: 'he / she / it / they'.", None, "person"),
]

# --------------------------------------------------------------------------- #
# 3. WORD TYPES (the words themselves)
# --------------------------------------------------------------------------- #

_PREPOSITIONS = [
    ("ἐν", "in, on, among  (+ dative)", "en", "preposition"),
    ("εἰς", "into, in, to, for  (+ accusative)", "eis", "preposition"),
    ("ἐκ / ἐξ", "out of, from  (+ genitive)", "ek / ex", "preposition"),
    ("ἀπό", "from, away from  (+ genitive)", "apo", "preposition"),
    ("διά", "through (+ gen); because of (+ acc)", "dia", "preposition"),
    ("πρός", "to, toward, with  (+ accusative)", "pros", "preposition"),
    ("ἐπί", "on, over, at, in the time of  (+ gen/dat/acc)", "epi", "preposition"),
    ("κατά", "down, against (+ gen); according to (+ acc)", "kata", "preposition"),
    ("μετά", "with (+ gen); after (+ acc)", "meta", "preposition"),
    ("περί", "concerning, about (+ gen); around (+ acc)", "peri", "preposition"),
    ("ὑπό", "by (agent) (+ gen); under (+ acc)", "hypo", "preposition"),
    ("παρά", "from (+ gen); beside/with (+ dat); alongside (+ acc)", "para", "preposition"),
    ("ὑπέρ", "on behalf of (+ gen); above/beyond (+ acc)", "hyper", "preposition"),
    ("σύν", "with, together with  (+ dative)", "syn", "preposition"),
    ("πρό", "before, in front of  (+ genitive)", "pro", "preposition"),
    ("ἀντί", "instead of, in place of, for  (+ genitive)", "anti", "preposition"),
    ("ἀνά", "up; distributively 'each'  (+ accusative)", "ana", "preposition"),
    ("ἐνώπιον", "before, in the presence of  (+ gen)", "enōpion", "improper prep."),
    ("ἕως", "until, as far as  (+ gen)", "heōs", "improper prep."),
    ("ἔμπροσθεν", "before, in front of  (+ gen)", "emprosthen", "improper prep."),
    ("ὀπίσω", "behind, after  (+ gen)", "opisō", "improper prep."),
    ("χωρίς", "without, apart from  (+ gen)", "chōris", "improper prep."),
    ("ἔξω", "outside, out of  (+ gen)", "exō", "improper prep."),
    ("ἐγγύς", "near  (+ gen/dat)", "engys", "improper prep."),
    ("ἄχρι(ς)", "until, as far as  (+ gen)", "achri", "improper prep."),
    ("μέχρι(ς)", "until, as far as  (+ gen)", "mechri", "improper prep."),
]

_CONJUNCTIONS = [
    ("καί", "and, also, even", "kai", "conjunction"),
    ("δέ", "but, and, now  (postpositive)", "de", "conjunction"),
    ("ἀλλά", "but, rather, yet", "alla", "conjunction"),
    ("γάρ", "for, because  (postpositive)", "gar", "conjunction"),
    ("οὖν", "therefore, then, so  (postpositive)", "oun", "conjunction"),
    ("ὅτι", "that, because; introduces quotations", "hoti", "conjunction"),
    ("ἵνα", "in order that, that  (+ subjunctive)", "hina", "conjunction"),
    ("ὡς", "as, like, that, when, how", "hōs", "conj./adverb"),
    ("ἐάν", "if  (+ subjunctive)", "ean", "conjunction"),
    ("εἰ", "if, whether", "ei", "conjunction"),
    ("ὅτε", "when", "hote", "conjunction"),
    ("ὥστε", "so that, therefore, with the result that", "hōste", "conjunction"),
    ("τε", "and  (enclitic; τε ... καί = 'both ... and')", "te", "conjunction"),
    ("οὐδέ", "and not, nor, not even", "oude", "conjunction"),
    ("μηδέ", "and not, nor, not even  (with non-indicative)", "mēde", "conjunction"),
    ("οὔτε", "neither, nor  (οὔτε ... οὔτε)", "oute", "conjunction"),
    ("εἴτε", "whether, if  (εἴτε ... εἴτε)", "eite", "conjunction"),
    ("ἤ", "or, than", "ē", "conjunction"),
    ("διό", "therefore, for this reason", "dio", "conjunction"),
    ("καθώς", "just as, as, according as", "kathōs", "conjunction"),
    ("ὅπως", "that, in order that, how", "hopōs", "conjunction"),
    ("πλήν", "however, but, nevertheless; except", "plēn", "conjunction"),
    ("ἄρα", "so, then, consequently", "ara", "conjunction"),
    ("ὅπου", "where, whereas", "hopou", "conjunction"),
]

_ADVERBS = [
    ("οὐ / οὐκ / οὐχ", "not  (with the indicative)", "ou", "adverb (neg.)"),
    ("μή", "not, lest  (with non-indicative moods)", "mē", "adverb (neg.)"),
    ("νῦν", "now, at present", "nyn", "adverb (time)"),
    ("οὕτως", "thus, in this way, so", "houtōs", "adverb (manner)"),
    ("πῶς", "how?  in what way?", "pōs", "adverb (interrog.)"),
    ("ποῦ", "where?", "pou", "adverb (interrog.)"),
    ("πότε", "when?", "pote", "adverb (interrog.)"),
    ("ἐκεῖ", "there, in that place", "ekei", "adverb (place)"),
    ("ὧδε", "here, in this place", "hōde", "adverb (place)"),
    ("εὐθύς / εὐθέως", "immediately, at once", "euthys", "adverb (time)"),
    ("πάλιν", "again, back", "palin", "adverb"),
    ("ἔτι", "still, yet", "eti", "adverb (time)"),
    ("ἤδη", "now, already", "ēdē", "adverb (time)"),
    ("μᾶλλον", "more, rather", "mallon", "adverb"),
    ("οὐκέτι", "no longer, no more", "ouketi", "adverb"),
    ("πάντοτε", "always, at all times", "pantote", "adverb (time)"),
    ("σήμερον", "today", "sēmeron", "adverb (time)"),
    ("τότε", "then, at that time", "tote", "adverb (time)"),
    ("ἔξω", "outside, out", "exō", "adverb (place)"),
    ("ταχύ / ταχέως", "quickly, soon", "tachy", "adverb"),
    ("ἀληθῶς", "truly, really", "alēthōs", "adverb"),
    ("μακράν", "far, far off", "makran", "adverb (place)"),
    ("ὅπου", "where  (relative)", "hopou", "adverb (place)"),
    ("ὅθεν", "from where, whence; therefore", "hothen", "adverb"),
    ("μόνον", "only, alone", "monon", "adverb"),
    ("καλῶς", "well, rightly", "kalōs", "adverb"),
]

_PARTICLES = [
    ("ἄν", "marks contingency/potential; often untranslatable", "an", "particle"),
    ("μέν", "on the one hand, indeed  (μέν ... δέ)", "men", "particle"),
    ("γε", "indeed, at least, even  (enclitic, emphatic)", "ge", "particle"),
    ("δή", "indeed, now, therefore  (emphatic)", "dē", "particle"),
    ("ναί", "yes, certainly, indeed", "nai", "particle"),
    ("οὐχί", "not, no  (strengthened form of οὐ)", "ouchi", "particle"),
    ("ἰδού", "behold! look! see!", "idou", "interjection"),
    ("ἴδε", "look! behold! see!", "ide", "interjection"),
    ("ἀμήν", "amen, truly, so be it", "amēn", "particle"),
    ("οὐαί", "woe! alas!", "ouai", "interjection"),
    ("ἆρα", "then, therefore  (interrogative particle)", "ara", "particle"),
    ("μήτι", "surely not?  (expects a 'no' answer)", "mēti", "particle"),
]

_PROPER_NOUNS = [
    ("Ἰησοῦς", "Jesus", "Iēsous", "person"),
    ("Χριστός", "Christ, Messiah, Anointed One", "Christos", "title"),
    ("Παῦλος", "Paul", "Paulos", "person"),
    ("Πέτρος", "Peter", "Petros", "person"),
    ("Σίμων", "Simon", "Simōn", "person"),
    ("Ἰωάννης", "John", "Iōannēs", "person"),
    ("Ἰάκωβος", "James", "Iakōbos", "person"),
    ("Ἀνδρέας", "Andrew", "Andreas", "person"),
    ("Φίλιππος", "Philip", "Philippos", "person"),
    ("Θωμᾶς", "Thomas", "Thōmas", "person"),
    ("Ἰούδας", "Judas, Judah, Jude", "Ioudas", "person"),
    ("Ματθαῖος", "Matthew", "Matthaios", "person"),
    ("Μαρία / Μαριάμ", "Mary, Miriam", "Maria", "person"),
    ("Μάρθα", "Martha", "Martha", "person"),
    ("Πιλᾶτος", "Pilate", "Pilatos", "person"),
    ("Ἡρῴδης", "Herod", "Hērōdēs", "person"),
    ("Καῖσαρ", "Caesar", "Kaisar", "title/person"),
    ("Μωϋσῆς", "Moses", "Mōusēs", "person"),
    ("Ἀβραάμ", "Abraham", "Abraam", "person (indecl.)"),
    ("Δαυίδ", "David", "Dauid", "person (indecl.)"),
    ("Ἰσαάκ", "Isaac", "Isaak", "person (indecl.)"),
    ("Ἰακώβ", "Jacob", "Iakōb", "person (indecl.)"),
    ("Ἰσραήλ", "Israel", "Israēl", "people/place (indecl.)"),
    ("Ἰερουσαλήμ / Ἱεροσόλυμα", "Jerusalem", "Ierousalēm", "place"),
    ("Γαλιλαία", "Galilee", "Galilaia", "place"),
    ("Ἰουδαία", "Judea", "Ioudaia", "place"),
    ("Ναζαρέθ", "Nazareth", "Nazareth", "place (indecl.)"),
    ("Καφαρναούμ", "Capernaum", "Kapharnaoum", "place (indecl.)"),
    ("Βηθλέεμ", "Bethlehem", "Bēthleem", "place (indecl.)"),
    ("Αἴγυπτος", "Egypt", "Aigyptos", "place"),
    ("Ῥώμη", "Rome", "Rhōmē", "place"),
    ("Σατανᾶς", "Satan, the Adversary", "Satanas", "person"),
    ("Βαρναβᾶς", "Barnabas", "Barnabas", "person"),
    ("Στέφανος", "Stephen", "Stephanos", "person"),
    ("Τιμόθεος", "Timothy", "Timotheos", "person"),
    ("Ἰωσήφ", "Joseph", "Iōsēph", "person (indecl.)"),
]

# --------------------------------------------------------------------------- #
# 4. FREQUENCY BANKS (top 300, in tiers of 100)
#    Ranks are approximate; treat each bank as a frequency tier.
# --------------------------------------------------------------------------- #

_BANK_1 = [
    ("ὁ, ἡ, τό", "the", "ho, hē, to", "article"),
    ("καί", "and, also, even", "kai", "conjunction"),
    ("αὐτός, -ή, -ό", "he, she, it; -self; the same", "autos", "pronoun"),
    ("σύ", "you (singular)", "su", "pronoun"),
    ("δέ", "but, and, now", "de", "conjunction"),
    ("ἐν", "in, on, among (+ dat)", "en", "preposition"),
    ("ἐγώ", "I", "egō", "pronoun"),
    ("εἰμί", "I am, exist", "eimi", "verb"),
    ("λέγω", "I say, speak", "legō", "verb"),
    ("εἰς", "into, to, for (+ acc)", "eis", "preposition"),
    ("οὐ, οὐκ, οὐχ", "not", "ou", "adverb"),
    ("ὅς, ἥ, ὅ", "who, which, that (relative)", "hos", "pronoun"),
    ("οὗτος, αὕτη, τοῦτο", "this; this one", "houtos", "pronoun"),
    ("θεός, -οῦ, ὁ", "God, god", "theos", "noun"),
    ("ὅτι", "that, because", "hoti", "conjunction"),
    ("πᾶς, πᾶσα, πᾶν", "all, every, whole", "pas", "adjective"),
    ("μή", "not, lest", "mē", "adverb"),
    ("γάρ", "for, because", "gar", "conjunction"),
    ("Ἰησοῦς, -οῦ, ὁ", "Jesus", "Iēsous", "proper noun"),
    ("ἐκ, ἐξ", "out of, from (+ gen)", "ek", "preposition"),
    ("ἐπί", "on, over, at (+ gen/dat/acc)", "epi", "preposition"),
    ("κύριος, -ου, ὁ", "lord, Lord, master", "kyrios", "noun"),
    ("ἔχω", "I have, hold", "echō", "verb"),
    ("πρός", "to, toward, with (+ acc)", "pros", "preposition"),
    ("γίνομαι", "I become, happen, am", "ginomai", "verb"),
    ("διά", "through (+ gen); because of (+ acc)", "dia", "preposition"),
    ("ἵνα", "in order that, that", "hina", "conjunction"),
    ("ἀπό", "from, away from (+ gen)", "apo", "preposition"),
    ("ἀλλά", "but, rather", "alla", "conjunction"),
    ("ἔρχομαι", "I come, go", "erchomai", "verb"),
    ("ποιέω", "I do, make", "poieō", "verb"),
    ("τις, τι", "someone, something; a certain", "tis", "pronoun"),
    ("τίς, τί", "who? what? why?", "tis", "pronoun"),
    ("ἄνθρωπος, -ου, ὁ", "man, person, human being", "anthrōpos", "noun"),
    ("Χριστός, -οῦ, ὁ", "Christ, Messiah, Anointed One", "Christos", "noun"),
    ("ὡς", "as, like, that, when", "hōs", "conj./adverb"),
    ("εἰ", "if, whether", "ei", "conjunction"),
    ("οὖν", "therefore, then, so", "oun", "conjunction"),
    ("κατά", "down, against (+ gen); according to (+ acc)", "kata", "preposition"),
    ("μετά", "with (+ gen); after (+ acc)", "meta", "preposition"),
    ("ὁράω", "I see, perceive", "horaō", "verb"),
    ("ἀκούω", "I hear, listen to", "akouō", "verb"),
    ("πολύς, πολλή, πολύ", "much, many; (adv.) often", "polys", "adjective"),
    ("δίδωμι", "I give, grant", "didōmi", "verb"),
    ("πατήρ, -τρός, ὁ", "father", "patēr", "noun"),
    ("ἡμέρα, -ας, ἡ", "day", "hēmera", "noun"),
    ("πνεῦμα, -ατος, τό", "spirit, wind, breath", "pneuma", "noun"),
    ("υἱός, -οῦ, ὁ", "son, descendant", "huios", "noun"),
    ("λαμβάνω", "I take, receive", "lambanō", "verb"),
    ("ἐκεῖνος, -η, -ο", "that; that one", "ekeinos", "pronoun"),
    ("λόγος, -ου, ὁ", "word, statement, message", "logos", "noun"),
    ("μέν", "on the one hand, indeed", "men", "particle"),
    ("οἶδα", "I know, understand", "oida", "verb"),
    ("γῆ, γῆς, ἡ", "earth, land, ground", "gē", "noun"),
    ("πίστις, -εως, ἡ", "faith, trust, belief", "pistis", "noun"),
    ("γινώσκω", "I know, come to know", "ginōskō", "verb"),
    ("ἅγιος, -α, -ον", "holy; (pl.) the saints", "hagios", "adjective"),
    ("ἀδελφός, -οῦ, ὁ", "brother, fellow believer", "adelphos", "noun"),
    ("ἀποκρίνομαι", "I answer, reply", "apokrinomai", "verb"),
    ("εἷς, μία, ἕν", "one", "heis", "adjective/number"),
    ("οὐρανός, -οῦ, ὁ", "heaven, sky", "ouranos", "noun"),
    ("οὐδείς, οὐδεμία, οὐδέν", "no one, nothing", "oudeis", "pronoun"),
    ("λαλέω", "I speak, say", "laleō", "verb"),
    ("δύναμαι", "I am able, can", "dynamai", "verb"),
    ("θέλω", "I wish, will, want", "thelō", "verb"),
    ("νόμος, -ου, ὁ", "law", "nomos", "noun"),
    ("λαός, -οῦ, ὁ", "people, nation", "laos", "noun"),
    ("ἴδιος, -α, -ον", "one's own, private", "idios", "adjective"),
    ("δύο", "two", "dyo", "number"),
    ("ἐάν", "if (+ subj)", "ean", "conjunction"),
    ("χείρ, χειρός, ἡ", "hand", "cheir", "noun"),
    ("εὑρίσκω", "I find, discover", "heuriskō", "verb"),
    ("ἄγγελος, -ου, ὁ", "angel, messenger", "angelos", "noun"),
    ("ὄχλος, -ου, ὁ", "crowd, multitude", "ochlos", "noun"),
    ("ἁμαρτία, -ας, ἡ", "sin", "hamartia", "noun"),
    ("δόξα, -ης, ἡ", "glory, splendor, honor", "doxa", "noun"),
    ("βασιλεία, -ας, ἡ", "kingdom, reign", "basileia", "noun"),
    ("ἔθνος, -ους, τό", "nation; (pl.) the Gentiles", "ethnos", "noun"),
    ("πόλις, -εως, ἡ", "city, town", "polis", "noun"),
    ("τότε", "then, at that time", "tote", "adverb"),
    ("ἐσθίω", "I eat", "esthiō", "verb"),
    ("Παῦλος, -ου, ὁ", "Paul", "Paulos", "proper noun"),
    ("καρδία, -ας, ἡ", "heart, inner self", "kardia", "noun"),
    ("πρῶτος, -η, -ον", "first, foremost", "prōtos", "adjective"),
    ("μαθητής, -οῦ, ὁ", "disciple, learner", "mathētēs", "noun"),
    ("ἀγαπάω", "I love", "agapaō", "verb"),
    ("οὕτως", "thus, in this way, so", "houtōs", "adverb"),
    ("Πέτρος, -ου, ὁ", "Peter", "Petros", "proper noun"),
    ("οἰκία / οἶκος", "house, household, home", "oikia / oikos", "noun"),
    ("πίπτω", "I fall", "piptō", "verb"),
    ("σῴζω", "I save, heal, deliver", "sōzō", "verb"),
    ("γράφω", "I write", "graphō", "verb"),
    ("ἀγαπητός, -ή, -όν", "beloved, dear", "agapētos", "adjective"),
    ("μέγας, μεγάλη, μέγα", "great, large", "megas", "adjective"),
    ("πιστεύω", "I believe, trust, have faith", "pisteuō", "verb"),
    ("βλέπω", "I see, look at", "blepō", "verb"),
    ("ἀφίημι", "I forgive, leave, permit", "aphiēmi", "verb"),
    ("ζάω", "I live, am alive", "zaō", "verb"),
    ("κόσμος, -ου, ὁ", "world, universe, humankind", "kosmos", "noun"),
    ("νεκρός, -ά, -όν", "dead; a dead person", "nekros", "adjective"),
]

_BANK_2 = [
    ("ἐξέρχομαι", "I go out, come out", "exerchomai", "verb"),
    ("εἰσέρχομαι", "I go in, enter", "eiserchomai", "verb"),
    ("ἀπέρχομαι", "I go away, depart", "aperchomai", "verb"),
    ("ζητέω", "I seek, look for", "zēteō", "verb"),
    ("καλέω", "I call, name, invite", "kaleō", "verb"),
    ("μένω", "I remain, abide, stay", "menō", "verb"),
    ("ζωή, -ῆς, ἡ", "life", "zōē", "noun"),
    ("ὥρα, -ας, ἡ", "hour, time, moment", "hōra", "noun"),
    ("ἀγάπη, -ης, ἡ", "love", "agapē", "noun"),
    ("ἀλήθεια, -ας, ἡ", "truth", "alētheia", "noun"),
    ("δοῦλος, -ου, ὁ", "servant, slave", "doulos", "noun"),
    ("ὄνομα, -ατος, τό", "name; reputation", "onoma", "noun"),
    ("γυνή, γυναικός, ἡ", "woman, wife", "gynē", "noun"),
    ("σάρξ, σαρκός, ἡ", "flesh, body, human nature", "sarx", "noun"),
    ("ἐγείρω", "I raise up, wake", "egeirō", "verb"),
    ("αἰών, -ῶνος, ὁ", "age, eternity; (adv.) forever", "aiōn", "noun"),
    ("ἀπόστολος, -ου, ὁ", "apostle, one sent", "apostolos", "noun"),
    ("βάλλω", "I throw, cast, put", "ballō", "verb"),
    ("ἀποθνῄσκω", "I die, am dying", "apothnēskō", "verb"),
    ("ἁμαρτωλός, -όν", "sinful; a sinner", "hamartōlos", "adjective/noun"),
    ("δικαιοσύνη, -ης, ἡ", "righteousness, justice", "dikaiosynē", "noun"),
    ("τηρέω", "I keep, guard, observe", "tēreō", "verb"),
    ("ἀγαθός, -ή, -όν", "good, useful", "agathos", "adjective"),
    ("ἀποστέλλω", "I send (out), commission", "apostellō", "verb"),
    ("φωνή, -ῆς, ἡ", "voice, sound, noise", "phōnē", "noun"),
    ("προφήτης, -ου, ὁ", "prophet", "prophētēs", "noun"),
    ("ἐγγίζω", "I come near, approach", "engizō", "verb"),
    ("δικαιόω", "I justify, declare righteous", "dikaioō", "verb"),
    ("ἐντολή, -ῆς, ἡ", "commandment, order", "entolē", "noun"),
    ("κρίνω", "I judge, decide, condemn", "krinō", "verb"),
    ("μόνος, -η, -ον", "only, alone", "monos", "adjective"),
    ("πούς, ποδός, ὁ", "foot", "pous", "noun"),
    ("θάλασσα, -ης, ἡ", "sea, lake", "thalassa", "noun"),
    ("αἷμα, -ατος, τό", "blood", "haima", "noun"),
    ("ὀφθαλμός, -οῦ, ὁ", "eye; sight", "ophthalmos", "noun"),
    ("ἀπόλλυμι", "I destroy, ruin; (mid.) perish", "apollymi", "verb"),
    ("λοιπός, -ή, -όν", "remaining, rest; (adv.) finally", "loipos", "adjective"),
    ("δόξα → δοξάζω", "I glorify, praise, honor", "doxazō", "verb"),
    ("κηρύσσω", "I proclaim, preach", "kēryssō", "verb"),
    ("μέλλω", "I am about to, intend", "mellō", "verb"),
    ("παραβολή, -ῆς, ἡ", "parable, comparison", "parabolē", "noun"),
    ("ἕτερος, -α, -ον", "other, another, different", "heteros", "adjective"),
    ("τέκνον, -ου, τό", "child", "teknon", "noun"),
    ("ἀνήρ, ἀνδρός, ὁ", "man, husband", "anēr", "noun"),
    ("ἀρχή, -ῆς, ἡ", "beginning, ruler, authority", "archē", "noun"),
    ("πληρόω", "I fill, fulfill, complete", "plēroō", "verb"),
    ("ἐρωτάω", "I ask, request", "erōtaō", "verb"),
    ("σῶμα, -ατος, τό", "body", "sōma", "noun"),
    ("δεῖ", "it is necessary, one must", "dei", "verb (impers.)"),
    ("θάνατος, -ου, ὁ", "death", "thanatos", "noun"),
    ("ἀγαθός → ἔργον", "work, deed, action", "ergon", "noun"),
    ("λίθος, -ου, ὁ", "stone", "lithos", "noun"),
    ("δύναμις, -εως, ἡ", "power, might, miracle", "dynamis", "noun"),
    ("παραδίδωμι", "I hand over, betray, deliver", "paradidōmi", "verb"),
    ("μέσος, -η, -ον", "middle, in the midst", "mesos", "adjective"),
    ("οὐδέ", "and not, nor, not even", "oude", "conjunction"),
    ("πονηρός, -ά, -όν", "evil, bad, wicked", "ponēros", "adjective"),
    ("χαίρω", "I rejoice; (greeting) hail", "chairō", "verb"),
    ("χαρά, -ᾶς, ἡ", "joy, gladness", "chara", "noun"),
    ("θεωρέω", "I look at, observe, perceive", "theōreō", "verb"),
    ("προσέρχομαι", "I come/go to, approach", "proserchomai", "verb"),
    ("καθίζω", "I sit down, seat", "kathizō", "verb"),
    ("ἄρτος, -ου, ὁ", "bread, loaf, food", "artos", "noun"),
    ("αἰτέω", "I ask, request", "aiteō", "verb"),
    ("ἀγγέλλω → εὐαγγέλιον", "gospel, good news", "euangelion", "noun"),
    ("δέχομαι", "I receive, accept, welcome", "dechomai", "verb"),
    ("πέμπω", "I send", "pempō", "verb"),
    ("γλῶσσα, -ης, ἡ", "tongue, language", "glōssa", "noun"),
    ("γραφή, -ῆς, ἡ", "Scripture, writing", "graphē", "noun"),
    ("κακός, -ή, -όν", "bad, evil, wrong", "kakos", "adjective"),
    ("μακάριος, -α, -ον", "blessed, happy, fortunate", "makarios", "adjective"),
    ("τιμή, -ῆς, ἡ", "honor, price, value", "timē", "noun"),
    ("ἀπόλλυμι → ἀπολύω", "I release, dismiss, divorce", "apolyō", "verb"),
    ("καιρός, -οῦ, ὁ", "time, appointed time, season", "kairos", "noun"),
    ("περιπατέω", "I walk (around), live", "peripateō", "verb"),
    ("φοβέομαι", "I fear, am afraid, respect", "phobeomai", "verb"),
    ("ἔτι", "still, yet", "eti", "adverb"),
    ("πληθος → πλῆθος, -ους, τό", "multitude, crowd", "plēthos", "noun"),
    ("σημεῖον, -ου, τό", "sign, miracle", "sēmeion", "noun"),
    ("ἐλπίς, -ίδος, ἡ", "hope, expectation", "elpis", "noun"),
    ("διδάσκω", "I teach", "didaskō", "verb"),
    ("διδάσκαλος, -ου, ὁ", "teacher", "didaskalos", "noun"),
    ("δοκέω", "I think, seem, suppose", "dokeō", "verb"),
    ("οὐαί", "woe! alas!", "ouai", "interjection"),
    ("μαρτυρέω", "I bear witness, testify", "martyreō", "verb"),
    ("κεφαλή, -ῆς, ἡ", "head", "kephalē", "noun"),
    ("ἀγρός, -οῦ, ὁ", "field, countryside", "agros", "noun"),
    ("συνάγω", "I gather together, assemble", "synagō", "verb"),
    ("πίνω", "I drink", "pinō", "verb"),
    ("τέλος, -ους, τό", "end, goal, tax", "telos", "noun"),
    ("ὥστε", "so that, therefore", "hōste", "conjunction"),
    ("φέρω", "I bear, carry, bring", "pherō", "verb"),
    ("ἀληθής, -ές", "true, truthful, real", "alēthēs", "adjective"),
    ("φῶς, φωτός, τό", "light", "phōs", "noun"),
    ("ἵστημι", "I stand, set, establish", "histēmi", "verb"),
    ("ἀριθμός → ἀρχιερεύς, -έως, ὁ", "high priest, chief priest", "archiereus", "noun"),
    ("γεννάω", "I beget, give birth to", "gennaō", "verb"),
    ("ἐκκλησία, -ας, ἡ", "church, assembly, congregation", "ekklēsia", "noun"),
    ("ἀπάγω → ἄγω", "I lead, bring, go", "agō", "verb"),
    ("μήτηρ, -τρός, ἡ", "mother", "mētēr", "noun"),
]

_BANK_3 = [
    ("ῥῆμα, -ατος, τό", "word, saying, thing", "rhēma", "noun"),
    ("δικαστής → δίκαιος, -α, -ον", "righteous, just, upright", "dikaios", "adjective"),
    ("ἀσπάζομαι", "I greet, welcome", "aspazomai", "verb"),
    ("πληρόω → πλήρης, -ες", "full, filled, complete", "plērēs", "adjective"),
    ("ψυχή, -ῆς, ἡ", "soul, life, self", "psychē", "noun"),
    ("σοφία, -ας, ἡ", "wisdom", "sophia", "noun"),
    ("δεξιός, -ά, -όν", "right (hand/side)", "dexios", "adjective"),
    ("θρόνος, -ου, ὁ", "throne", "thronos", "noun"),
    ("ἐπαγγελία, -ας, ἡ", "promise", "epangelia", "noun"),
    ("ὁδός, -οῦ, ἡ", "way, road, journey", "hodos", "noun"),
    ("πωλέω → θέλημα, -ατος, τό", "will, desire", "thelēma", "noun"),
    ("ἀνοίγω", "I open", "anoigō", "verb"),
    ("βαπτίζω", "I baptize, dip, immerse", "baptizō", "verb"),
    ("σπείρω", "I sow (seed)", "speirō", "verb"),
    ("μισέω", "I hate, detest", "miseō", "verb"),
    ("διώκω", "I pursue, persecute", "diōkō", "verb"),
    ("κρατέω", "I grasp, hold, seize", "krateō", "verb"),
    ("ὄρος, -ους, τό", "mountain, hill", "oros", "noun"),
    ("οὐκέτι", "no longer, no more", "ouketi", "adverb"),
    ("πάσχω", "I suffer, experience", "paschō", "verb"),
    ("ἐπερωτάω", "I ask, question, request", "eperōtaō", "verb"),
    ("φυλάσσω", "I guard, keep, obey", "phylassō", "verb"),
    ("θεραπεύω", "I heal, cure, serve", "therapeuō", "verb"),
    ("νύξ, νυκτός, ἡ", "night", "nyx", "noun"),
    ("ἀριθμός, -οῦ, ὁ", "number", "arithmos", "noun"),
    ("χρόνος, -ου, ὁ", "time, period", "chronos", "noun"),
    ("θαυμάζω", "I marvel, wonder, am amazed", "thaumazō", "verb"),
    ("φαίνω", "I shine, appear, seem", "phainō", "verb"),
    ("ἐλεέω", "I have mercy, show pity", "eleeō", "verb"),
    ("ἔλεος, -ους, τό", "mercy, compassion", "eleos", "noun"),
    ("ἐπιθυμία, -ας, ἡ", "desire, longing, lust", "epithymia", "noun"),
    ("πρεσβύτερος, -α, -ον", "older, elder", "presbyteros", "adjective/noun"),
    ("συνέδριον → ἱερόν, -οῦ, τό", "temple (precincts)", "hieron", "noun"),
    ("θυσία, -ας, ἡ", "sacrifice, offering", "thysia", "noun"),
    ("ναός, -οῦ, ὁ", "temple, sanctuary", "naos", "noun"),
    ("βασιλεύς, -έως, ὁ", "king", "basileus", "noun"),
    ("διαθήκη, -ης, ἡ", "covenant, will, testament", "diathēkē", "noun"),
    ("ἀκολουθέω", "I follow, accompany (+ dat)", "akoloutheō", "verb"),
    ("παρακαλέω", "I urge, encourage, comfort", "parakaleō", "verb"),
    ("σταυρόω", "I crucify", "stauroō", "verb"),
    ("σταυρός, -οῦ, ὁ", "cross", "stauros", "noun"),
    ("ἐπιστολή → ἐπιγινώσκω", "I know fully, recognize", "epiginōskō", "verb"),
    ("φυλή, -ῆς, ἡ", "tribe, nation, people", "phylē", "noun"),
    ("ὑπάγω", "I go away, depart", "hypagō", "verb"),
    ("ὑπάρχω", "I am, exist; (n. pl.) possessions", "hyparchō", "verb"),
    ("χρεία, -ας, ἡ", "need, necessity", "chreia", "noun"),
    ("ἐντέλλομαι → σπέρμα, -ατος, τό", "seed, offspring, descendant", "sperma", "noun"),
    ("μαρτυρία, -ας, ἡ", "testimony, witness", "martyria", "noun"),
    ("πειράζω", "I test, tempt, try", "peirazō", "verb"),
    ("πρόσωπον, -ου, τό", "face, presence, appearance", "prosōpon", "noun"),
    ("ἀπολαμβάνω → λοιπός → πλοῖον, -ου, τό", "boat, ship", "ploion", "noun"),
    ("θύρα, -ας, ἡ", "door, gate, entrance", "thyra", "noun"),
    ("γάμος → ἀσθενέω", "I am weak, sick", "astheneō", "verb"),
    ("πλανάω", "I lead astray, deceive; (pass.) wander", "planaō", "verb"),
    ("ὀργή, -ῆς, ἡ", "wrath, anger", "orgē", "noun"),
    ("ἐπιτίθημι → τίθημι", "I put, place, lay, set", "tithēmi", "verb"),
    ("προσκυνέω", "I worship, bow down (+ dat)", "proskyneō", "verb"),
    ("μνημεῖον, -ου, τό", "tomb, grave, monument", "mnēmeion", "noun"),
    ("διάβολος, -ον", "slanderous; (n.) the devil", "diabolos", "adjective/noun"),
    ("πρόβατον, -ου, τό", "sheep", "probaton", "noun"),
    ("τυφλός, -ή, -όν", "blind; a blind person", "typhlos", "adjective"),
    ("ἐκβάλλω", "I cast out, drive out, send out", "ekballō", "verb"),
    ("ἐπιστρέφω", "I turn (back), return, convert", "epistrephō", "verb"),
    ("σκότος, -ους, τό", "darkness", "skotos", "noun"),
    ("ἐλεύθερος, -α, -ον", "free; a free person", "eleutheros", "adjective"),
    ("ὑποτάσσω", "I subject, subordinate", "hypotassō", "verb"),
    ("οἰκοδομέω", "I build, edify", "oikodomeō", "verb"),
    ("μιμνῄσκομαι", "I remember, recall", "mimnēskomai", "verb"),
    ("γεωργός → γενεά, -ᾶς, ἡ", "generation, age, family", "genea", "noun"),
    ("ἄρχω", "I rule (+ gen); (mid.) I begin", "archō", "verb"),
    ("ἄρχων, -οντος, ὁ", "ruler, official, prince", "archōn", "noun"),
    ("φανερόω", "I reveal, make known, show", "phaneroō", "verb"),
    ("πρόσκομμα → χωρίζω", "I separate, divide; (pass.) depart", "chōrizō", "verb"),
    ("ἀπαγγέλλω", "I report, announce, tell", "apangellō", "verb"),
    ("πάσχα, τό", "Passover", "pascha", "noun (indecl.)"),
    ("κράζω", "I cry out, call out, shout", "krazō", "verb"),
    ("κρίσις, -εως, ἡ", "judgment, condemnation", "krisis", "noun"),
    ("δεσμός → φυλακή, -ῆς, ἡ", "prison, guard, watch", "phylakē", "noun"),
    ("γραμματεύς, -έως, ὁ", "scribe, expert in the law", "grammateus", "noun"),
    ("Φαρισαῖος, -ου, ὁ", "Pharisee", "Pharisaios", "noun"),
    ("δαιμόνιον, -ου, τό", "demon, evil spirit", "daimonion", "noun"),
    ("θηρίον, -ου, τό", "wild animal, beast", "thērion", "noun"),
    ("καρπός, -οῦ, ὁ", "fruit, harvest, result", "karpos", "noun"),
    ("μισθός, -οῦ, ὁ", "wages, reward, pay", "misthos", "noun"),
    ("νεφέλη, -ης, ἡ", "cloud", "nephelē", "noun"),
    ("ὀλίγος, -η, -ον", "little, few, small", "oligos", "adjective"),
    ("ἴσχυρός → ἰσχύω", "I am strong, able, healthy", "ischyō", "verb"),
    ("δεῖπνον → δουλεύω", "I serve, am a slave (+ dat)", "douleuō", "verb"),
    ("ἐπιθυμέω", "I desire, long for, covet", "epithymeō", "verb"),
    ("ἀναβαίνω", "I go up, ascend, come up", "anabainō", "verb"),
    ("καταβαίνω", "I go down, descend, come down", "katabainō", "verb"),
    ("μετανοέω", "I repent, change my mind", "metanoeō", "verb"),
    ("μετάνοια, -ας, ἡ", "repentance, change of mind", "metanoia", "noun"),
    ("συνείδησις → ἁγιάζω", "I sanctify, consecrate, make holy", "hagiazō", "verb"),
    ("ἀσθενής, -ές", "weak, sick, feeble", "asthenēs", "adjective"),
    ("βιβλίον, -ου, τό", "book, scroll, document", "biblion", "noun"),
    ("ἐπικαλέω → βαστάζω", "I carry, bear, endure", "bastazō", "verb"),
    ("παρρησία, -ας, ἡ", "boldness, confidence, openness", "parrēsia", "noun"),
    ("σκανδαλίζω", "I cause to stumble, offend", "skandalizō", "verb"),
    ("τελέω", "I finish, complete, fulfill", "teleō", "verb"),
]

# --------------------------------------------------------------------------- #
# Assemble
# --------------------------------------------------------------------------- #

DECKS = [
    # --- Alphabet ---
    {"group": "Alphabet", "slug": "alpha-minuscule", "name": "Minuscule",
     "subtitle": "lowercase letters, names & sounds", "cards": _MINUSCULE},
    {"group": "Alphabet", "slug": "alpha-uncial", "name": "Uncial",
     "subtitle": "majuscule (capital) letters", "cards": _UNCIAL},

    # --- Grammar terms ---
    {"group": "Grammar terms", "slug": "gram-parts", "name": "Parts of speech",
     "subtitle": "noun, verb, adjective …", "cards": _PARTS_OF_SPEECH},
    {"group": "Grammar terms", "slug": "gram-cases", "name": "Noun cases",
     "subtitle": "the five cases", "cards": _CASES},
    {"group": "Grammar terms", "slug": "gram-tenses", "name": "Verb tenses",
     "subtitle": "present, aorist, perfect …", "cards": _TENSES},
    {"group": "Grammar terms", "slug": "gram-voices", "name": "Verb voices",
     "subtitle": "active, middle, passive", "cards": _VOICES},
    {"group": "Grammar terms", "slug": "gram-moods", "name": "Verb moods",
     "subtitle": "indicative, subjunctive …", "cards": _MOODS},
    {"group": "Grammar terms", "slug": "gram-verbals", "name": "Verbal forms",
     "subtitle": "infinitive & participle", "cards": _VERBALS},
    {"group": "Grammar terms", "slug": "gram-number-gender", "name": "Number, gender & person",
     "subtitle": "the agreement categories", "cards": _NUMBER_GENDER},

    # --- Word types ---
    {"group": "Word types", "slug": "type-prepositions", "name": "Prepositions",
     "subtitle": "with the cases they govern", "cards": _PREPOSITIONS},
    {"group": "Word types", "slug": "type-conjunctions", "name": "Conjunctions",
     "subtitle": "connectors & clause markers", "cards": _CONJUNCTIONS},
    {"group": "Word types", "slug": "type-adverbs", "name": "Adverbs",
     "subtitle": "manner, time, place, negation", "cards": _ADVERBS},
    {"group": "Word types", "slug": "type-particles", "name": "Particles",
     "subtitle": "small words & interjections", "cards": _PARTICLES},
    {"group": "Word types", "slug": "type-proper-nouns", "name": "Proper nouns",
     "subtitle": "people & places", "cards": _PROPER_NOUNS},

    # --- Frequency banks ---
    {"group": "Frequency banks", "slug": "freq-1", "name": "Bank 1 · top 100",
     "subtitle": "the most common words in the NT", "cards": _BANK_1},
    {"group": "Frequency banks", "slug": "freq-2", "name": "Bank 2 · 101–200",
     "subtitle": "high-frequency tier 2", "cards": _BANK_2},
    {"group": "Frequency banks", "slug": "freq-3", "name": "Bank 3 · 201–300",
     "subtitle": "high-frequency tier 3", "cards": _BANK_3},
]
